### ISSUE TITLE
Failed to access the WSDL at: file:./src/main/resources/wsdl/some_service.wsdl

### ISSUE THREAD

**Issue by ramu-phanimukla** [nilsmagnus/wsdl2java#125]
Plugin generated source file `SomeService.java` has reference to project dir structure which in runtime doesn't hold true. Below is the generated code:
```
static {
    URL url = null;
    try {
      url = new URL("file:./src/main/resources/wsdl/some_service.wsdl");
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(SomeService.class.getName())
          .log(
              java.util.logging.Level.INFO,
              "Can not initialize the default wsdl from {0}",
              "file:./src/main/resources/wsdl/some_service.wsdl");
    }
    WSDL_LOCATION = url;
  }
```
In `springboot` based applications, the generated jar has below folder structure:
```
- BOOT-INF
   - classes
      - wsdl
- META-INF
- org
```
Since the actual folder structure and what is seen in the generated class are different, it results in `Failed to access the WSDL at: file:./src/main/resources/wsdl/some_service.wsdl` error during runtime

**Comment by rbraeunlich** [comment]
Hey @ramu-phanimukla and whoever stumbles upon this bug,
I think you can work around this problem by passing the `-wsdlLocation` parameter in the gradle plugin. This changes the location in the annotation and the generated code. So e.g.
```
    wsdlsToGenerate = listOf(
        listOf("-client", "-p", "com.my.package.gen", "-wsdlLocation", "/wsdl/myFile.wsdl", "$wsdlDir/myFile.wsdl")
    )
```
I haven't tested it fully yet but I didn't want to forget to post this here ;)
