### ISSUE TITLE
Problem generating java code from plugin

### ISSUE THREAD

**Issue by strindberg** [nilsmagnus/wsdl2java#19]
I have trouble generating java code from our wsdl using this plugin. I have created an example project here: https://github.com/strindberg/wsdl-gen-plugin.git.

I have also created an equivalent project, running wsdl2java through manual setup. This approach works. You can find that example here: https://github.com/strindberg/wsdl-gen-manual.git

When I run gradle using the plugin, I get the following errors:
% gradle clean build
:deleteGeneratedSources
:clean UP-TO-DATE
:wsdl2java FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wsdl2java'.
> jar:file:/Users/jesper/.m2/repository/org/apache/cxf/cxf-tools-common/2.7.10/cxf-tools-common-2.7.10.jar!/org/apache/cxf/tools/common/jaxb/W3CEPRJaxbBinding_jaxb22.xml [44,28]: cvc-complex-type.3.2.2: Attribute 'xjc:recursive' is not allowed to appear in element 'class'.
  jar:file:/Users/jesper/.m2/repository/org/apache/cxf/cxf-tools-common/2.7.10/cxf-tools-common-2.7.10.jar!/org/apache/cxf/tools/common/jaxb/W3CEPRJaxbBinding_jaxb22.xml [40,28]: cvc-complex-type.3.2.2: Attribute 'xjc:recursive' is not allowed to appear in element 'class'.
  jar:file:/Users/jesper/.m2/repository/org/apache/cxf/cxf-tools-common/2.7.10/cxf-tools-common-2.7.10.jar!/org/apache/cxf/tools/common/jaxb/W3CEPRJaxbBinding_jaxb22.xml [36,28]: cvc-complex-type.3.2.2: Attribute 'xjc:recursive' is not allowed to appear in element 'class'.
  jar:file:/Users/jesper/.m2/repository/org/apache/cxf/cxf-tools-common/2.7.10/cxf-tools-common-2.7.10.jar!/org/apache/cxf/tools/common/jaxb/W3CEPRJaxbBinding_jaxb22.xml [32,28]: cvc-complex-type.3.2.2: Attribute 'xjc:recursive' is not allowed to appear in element 'class'.
  jar:file:/Users/jesper/.m2/repository/org/apache/cxf/cxf-tools-common/2.7.10/cxf-tools-common-2.7.10.jar!/org/apache/cxf/tools/common/jaxb/W3CEPRJaxbBinding_jaxb22.xml [28,28]: cvc-complex-type.3.2.2: Attribute 'xjc:recursive' is not allowed to appear in element 'class'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by nilsmagnus** [comment]
It is probably related to the jaxb-implementation you are using. I notice that in the working example you are using "org.jvnet.jaxb2_commons:jaxb2-basics:0.6.4". You could try to add this as a dependency to the plugin, and exclude the other jaxb-version.

**Comment by strindberg** [comment]
I have tried adding the following to the build.gradle in the non-functioning project using the plugin:

    dependencies {
        wsdl2java "org.jvnet.jaxb2_commons:jaxb2-basics:0.6.4"
    }

This does not work, however. Same error as before. According to the jaxb2-basics documentation, having this dependency on the classpath should make it available as a wsdl2java plugin.

If I do a 

    gradle dependencies

I can see that this dependency is indeed in the dependency list for the wsdl2java configuration:

wsdl2java
+--- org.jvnet.jaxb2_commons:jaxb2-basics:0.6.4
|    +--- org.jvnet.jaxb2_commons:jaxb2-basics-runtime:0.6.4
|    +--- org.jvnet.jaxb2_commons:jaxb2-basics-tools:0.6.4
|    |    +--- commons-beanutils:commons-beanutils:1.7.0
|    |    |    \--- commons-logging:commons-logging:1.0.3 -> 1.1.1
|    |    +--- commons-lang:commons-lang:2.2 -> 2.4
|    |    +--- commons-logging:commons-logging:1.1.1
|    |    \--- org.jvnet.jaxb2_commons:jaxb2-basics-runtime:0.6.4
|    \--- com.google.code.javaparser:javaparser:1.0.8
+--- org.apache.cxf:cxf-tools:2.7.10
+--- org.apache.cxf:cxf-tools-wsdlto-databinding-jaxb:2.7.10
|    +--- com.sun.xml.bind:jaxb-xjc:2.1.13
...

To me, it seems as though the dependency is not in effect when generating the java code.

I am note sure which dependency you're suggesting I remove.

**Comment by nilsmagnus** [comment]
Ok. To add custom dependencies to this plugin I suspect you will have to do it in an "afterEvaluate" closure because of the way the plugin handles dynamic cxf-dependencies. 

You could try to add an project.afterEvaluate closure to your build-script and make it work this way.

**Comment by nilsmagnus** [comment]
Sorry, I think I found something here. cxf 2.7.10 has a dependency to jaxb-2.1 which is probably in use here. When using jaxb 2.2 the problem should go away. So you have to exclude the dependencies 

    com.sun.xml.bind:jaxb-xjc:2.1.13
    com.sun.xml.bind:jaxb-impl:2.1.13
From the

**Comment by missourian55** [comment]
I appreciate @strindberg and @nilsmagnus , based on your examples,  I am able to use jaxb2basics with wsdl2java plugin.
