### ISSUE TITLE
Specifying -exsh true not producing implicit SOAP headers

### ISSUE THREAD

**Issue by sguillory6** [nilsmagnus/wsdl2java#21]
I am configuring the plugin as follows, however, the "-exsh true" argument is being ignored, i.e. the implicit SOAP header parameters are not in the generated source:

wsdl2java {
    wsdlDir = file("$projectDir/src/main/resources")
    generatedWsdlDir = file("$projectDir/build/generated-sources/wsdl")  // target directory for generated source code
    wsdlsToGenerate = [   //  2d-array of wsdls and cxf-parameters
                          ['-exsh', 'true', "$projectDir/src/main/resources/ResponsysWS57.wsdl"],
                          ['-exsh', 'true', "$projectDir/src/main/resources/ResponsysWS_Level1.wsdl"],
                          ['-exsh', 'true', "$projectDir/src/main/resources/TriggeredMessageWS.wsdl"]
    ]
    cxfVersion = "2.5.7"
}

**Comment by nilsmagnus** [comment]
try adding the cxf-rt-binding-soap as a dependency to the plugin (as stated in the docs for the option, http://cxf.apache.org/docs/wsdl-to-java.html )

**Comment by sguillory6** [comment]
Yeah, I got it working by doing this (was going to post this earlier but went to lunch first):

buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath "org.apache.cxf:cxf-rt-bindings-soap:2.5.7"
        classpath "org.apache.velocity:velocity:1.7"
    }
}

plugins {
    id "no.nils.wsdl2java" version "0.6"
}
