### ISSUE TITLE
Hard References to wsdl in java classes

### ISSUE THREAD

**Issue by rickygarg** [nilsmagnus/wsdl2java#25]
The generated service class gives a hard reference to all path references to the wsdl file. 

Examples:
1.  @WebServiceClient(name = "TestServiceService",  wsdlLocation = "file:/home/user/..../wsdlFile.wsdl", ....)
2.  url = new URL("file:/home/user/...../wsdlFile.wsdl");

CXF Version is 3.1.0. Assume that all paths in wsdl2java options are relative to $projectDir.

Also the following will be useful additions that are already present in the Maven plugin:
1. 'Mark as generated' option.
2. Ability to specify a binding file.
3. No address binding
4. Supplying serial version for web faults.

Thanks so much!

**Comment by jdevora** [comment]
Hi,
I use the following to get a relative classpath 
 wsdlsToGenerate = [
			["-verbose", "-wsdlLocation", "../wsdl/example.wsdl","$projectDir/src/main/resources/wsdl/example.wsdl"]
			
    ]

**Comment by nilsmagnus** [comment]
@rickygarg did @jdevora s comment resolve the problem for you?

**Comment by rickygarg** [comment]
@nilsmagnus I decided to migrate that project from wsdl to wadl before the
comment by @jdevora

**Comment by jeffnelson** [comment]
@jdevora 's comment resolved the issue for me
