### ISSUE TITLE
cxfVersion for xsd2java?

### ISSUE THREAD

**Issue by jdevora** [nilsmagnus/wsdl2java#29]
Hi,

I have to work in a legacy environment and I need to use  cxfVersion = "2.3.1"
Now I have class version issues and running 
    gradle dependencies

I see :
```
    wsdl2java
        +--- org.apache.cxf:cxf-tools-wsdlto-databinding-jaxb:2.3.1
        |    +--- com.sun.xml.bind:jaxb-xjc:2.1.13
        |    +--- com.sun.xml.bind:jaxb-impl:2.1.13
    ...
    xsd2java
        +--- com.sun.xml.bind:jaxb-xjc:2.2.5
          \--- com.sun.xml.bind:jaxb-impl:2.2.5
```
I don't think is behind the problem, but I just realized that there isn't a way to set the cxf version/jaxb on xsd2java

**Comment by nilsmagnus** [comment]
Hi @jdevora . I am thinking of excluding the xsd-task from this plugin in the next release since it is a source of confusion and errors like you are reporting.

**Comment by nilsmagnus** [comment]
Version 0.8 is now live, I would be thankful if you try it in your project and report back if it works for you.
