### ISSUE TITLE
Not able to specify the wsdlLocation for the generated code.

### ISSUE THREAD

**Issue by aayushgupta** [nilsmagnus/wsdl2java#31]
I want to specify the relative path to wsdl file in the generated Java code. As of now the plugin adds the absolute path to wsdl file. e.g.

@WebServiceClient(name = "ServiceActivation", 
                  wsdlLocation = "file:/C:/portal/workspace/src/main/wsdl/ServiceActivation40.wsdl",
                  targetNamespace = "http://xyz.com/ws/4.0/serviceactivation") 

How can I cange it to append "classpath:ServiceActivation40.wsdl" instead of absolute path. I have been able to achieve it with maven.

**Comment by Vandalko** [comment]
You may use `wsdlLocation` parameter as explained here http://cxf.apache.org/docs/wsdl-to-java.html 

```groovy
wsdl2java {
    wsdlsToGenerate = [
            ['-wsdlLocation', 'classpath:services/Service.wsdl', 'src/main/resources/services/Service.wsdl']
    ]
}

```

**Comment by BGligorijevic** [comment]
This does not seem to work for me or I am using it wrongly:

wsdl2java {
    wsdlsToGenerate = [
            ['-p','com.mypackage', '- autoNameResolution',"$projectDir/src/main/resources/wsdl/IMWOService.xml"],
            ['-wsdlLocation', 'classpath:wsdl/IMWOService.wsdl', 'src/main/resources/wsdl/Service.wsdl']
    ]
    generatedWsdlDir = file("$projectDir/src/main/java/")
    wsdlDir = file("$projectDir/src/main/resources/wsdl")
}

All I want to achieve is being able to specify my local relative WSDL file under src/main/resources/wsdl/Service.wsdl and generate classes under com.mypackage.

Any ideas?
Thanks

**Comment by BGligorijevic** [comment]
This is the correct solution:

wsdl2java {
    wsdlsToGenerate = [
            ["-p", "com.mypackage", "-wsdlLocation", "classpath:wsdl/Service.xml", "$projectDir/src/main/resources/wsdl/Service.xml"]
    ]
    generatedWsdlDir = file("$projectDir/src/main/java")
    wsdlDir = file("$projectDir/src/main/resources/wsdl")
}

Sources will be generated under src/main/java/com/mypackage and the WSDL file will be relative in the generated classes.
