### ISSUE TITLE
Same version used for CXF and CXF Plugins

### ISSUE THREAD

**Issue by brynjargles** [nilsmagnus/wsdl2java#37]
The version of the CXF Plugins lags behind the CXF tools. Currently the latest version of org.apache.cxf.xjcplugins:cxf-xjc-ts is 3.0.5 while the latest version of the org.apache.cxf:cxf-tools is 3.1.4. When setting the wsdl2java cxfVersion to 3.1.4 when using the -xjc-Xts flag, the build fails.

To solve this I propose that a separate cxfToolsVersion option is added. This could default to the value of cxfVersion.

**Comment by KrauseStefan** [comment]
With the new version of `wsdl2Java` this has become a problem for us as well.
Before the plugins where not added as dependencies unless the arguments `-xjc-Xts` or `-xjc-Xbg` where added.

This problem only appears when you run with a fixed `cxfVersion` version as the default value for the version is `+` this allows the latest version to be used, which is not necessarily the same version!

We have for a long time used `cxfVersion = '3.3.2'` which is not brand new, that version does not exist for `org.apache.cxf.xjcplugins:cxf-xjc-ts` and `org.apache.cxf.xjcplugins:cxf-xjc-boolean`.

We need a separate version for these plugins.

There already exists an old pull request for fixing this #60, I will create a new one targeting the lastest version of `wsdl2java`, I took the liberty to re add the argument flag conditions mentioned earlier.

Let me know if that is not desirable.
