### ISSUE TITLE
Rebuild source on build

### ISSUE THREAD

**Issue by zack3582** [nilsmagnus/wsdl2java#41]
Hi

I'm in the process to migrate all my source from ant to gradle.

Thanks for this plugin it works perfectly for me, and was easy to implement. I just have one question is there a way that after the first download of the WSDL and xsd files on the first time of the generated sources code, not to do this on each clean and build and only do this when the WSDL file was modify, The reason from this is that I don't always have access to the 3rd Party WSDL and there link is down, and I'm then not able to generate the sources, and compile my source,

The other question is that some of these 3rd parties don't have access to QA platforms and only production so i do have a copy off all the WSDL and xsd files, can i get this plugin to make use of the local files instead of trying to connect to their platform and downlaod all the files to generate this 

Please see build script below

buildscript{
    dependencies {
        classpath 'no.nils:wsdl2java:0.8'
    }
}

apply plugin :'java'
apply plugin :'no.nils.wsdl2java'

wsdl2java{
     wsdlsToGenerate = [
            [ projectDir.absolutePath + "/src/main/resources/wsdl/webservices.wsdl"]
    ]
    generatedWsdlDir = file(projectDir.absolutePath + "/src/main/java/")
    wsdlDir = file(projectDir.absolutePath + "/src/main/resources/wsdl")
    cxfVersion = "3.0.1"
}

**Comment by jskovjyskebankdk** [comment]
I have written a task to download WSDLs.
This task "localizes" the WSDLs and XDSs, so the original sources are not accessed by IDE or runtime.

We only activate it when we know there are changes upstream (and thus commit the generated source in git).

I will see if I can get time to add the task to this project sometime next week. But I will not promise that I do!



There is already an option you can set to avoid deleting the generated sources:

wsdl2java {
  deleteGeneratedSourcesOnClean = false
}

**Comment by zack3582** [comment]
Thank you very much this will help me allot

**Comment by nilsmagnus** [comment]
@jskovjyskebankdk could you add the option to the example in README ?

**Comment by jskovjyskebankdk** [comment]
I updated the documentation.

**Comment by nilsmagnus** [comment]
Nice :)

I added you as a contributor, so feel free to do whatever changes you think
is useful and sane.

-Nils

On Mon, Jan 25, 2016 at 8:23 AM Jesper Skov <notifications@github.com>
wrote:

> I updated the documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilsmagnus/wsdl2java/issues/41#issuecomment-174424869>
> .
>
-- 
-Nils

**Comment by jskovjyskebankdk** [comment]
@zack3582, I have created a new issue for the fetcher task (nilsmagnus/wsdl2java#46).
Unfortunately, I cannot easily make it available to you.
