### ISSUE TITLE
Dependency issue - "Could not find no.nils:wsdl2java:0.9"

### ISSUE THREAD

**Issue by cleankod** [nilsmagnus/wsdl2java#43]
The dependency:
```
'no.nils:wsdl2java:0.9'
```

Does not work. Gradle complains:
```
> Could not find no.nils:wsdl2java:0.9.
     Searched in the following locations:
         https://jcenter.bintray.com/no/nils/wsdl2java/0.9/wsdl2java-0.9.pom
         https://jcenter.bintray.com/no/nils/wsdl2java/0.9/wsdl2java-0.9.jar
```
Did you publish the artifact correctly?

**Comment by nilsmagnus** [comment]
Ouch. Thanks for the feedback. Should be fixed now.

**Comment by cleankod** [comment]
The workaround seems to be:

1. Add repository:

    ```gradle
   maven {
       url  "http://dl.bintray.com/nilsmagnus/maven"
   }
    ```

2. Change dependency to:

    ```gradle
   classpath 'no.nils:plugin:0.9'
    ```


So I guess the artifact is wrongly published (`artifactId` is `plugin`).

**Comment by cleankod** [comment]
Whoa! That was fast! Thanks. I confirm that it works! :+1:

**Comment by touchpeak** [comment]
Just ran into this same issue today. I have used the same version of this plugin successfully on a different application several times before. Tried to add it to another application today and suddenly Gradle is complaining that I cannot find it from the repo. Am I missing something, is it published correctly?

```
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find no.nils:wsdl2java:0.10.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/no/nils/wsdl2java/0.10/wsdl2java-0.10.pom
  - https://repo.maven.apache.org/maven2/no/nils/wsdl2java/0.10/wsdl2java-0.10.jar
```
