### ISSUE TITLE
Not able to use the namespace option (-p)

### ISSUE THREAD

**Issue by knoxor** [nilsmagnus/wsdl2java#48]
Hi,
I've been trying to use the -p option to replace the wsdl namespace with my own package name but not sure how to do this. I have tried various options but no success.

Any ideas ?

`
wsdl2java{
    wsdlsToGenerate = [
            ["${projectDir}/src/main/resources/service.wsdl"],
            ["-p","src/main/java/mypackagename"]
//         ["-p", "namspaceToReplace", "src/main/java/mypackagename"]
    ]
    generatedWsdlDir = file("$projectDir/src/main/java")
    wsdlDir = file("$projectDir/src/main/resources")
    locale = Locale.ENGLISH
}
`

**Comment by jskovjyskebankdk** [comment]
This should work.

```
wsdl2java{ 
  wsdlsToGenerate = [
   ["-p","my.package.name", file("src/main/resources/service.wsdl")]
  ]
 generatedWsdlDir = file("src/main/java")
 wsdlDir = file("src/main/resources")
 locale = Locale.ENGLISH 
}
```

**Comment by knoxor** [comment]
thanks!
