### ISSUE TITLE
Gradle-Build-Error since upgrade Android Studio to 2.x

### ISSUE THREAD

**Issue by graf-semmel** [nilsmagnus/wsdl2java#54]
Hi, i updated Android Studio from 1.5.1 to 2.0 today and get the following error during gradle build now. I definitely **deactivated** the **offline** mode. Any suggestions?? 

>Error:Execution failed for task ':opendataconnector:wsdl2java'.
> Could not resolve all dependencies for configuration ':opendataconnector:wsdl2java'.
   > Could not resolve org.apache.cxf:cxf-tools-wsdlto-databinding-jaxb:+.
     Required by:
         tip-champion:opendataconnector:unspecified
      > No cached version listing for org.apache.cxf:cxf-tools-wsdlto-databinding-jaxb:+ available for offline mode.
      > No cached version listing for org.apache.cxf:cxf-tools-wsdlto-databinding-jaxb:+ available for offline mode.
   > Could not resolve org.apache.cxf:cxf-tools-wsdlto-frontend-jaxws:+.
     Required by:
         tip-champion:opendataconnector:unspecified
      > No cached version listing for org.apache.cxf:cxf-tools-wsdlto-frontend-jaxws:+ available for offline mode.
      > No cached version listing for org.apache.cxf:cxf-tools-wsdlto-frontend-jaxws:+ available for offline mode.

**Update**
I updated gradle version too and built the project with gradle, not from android studio. This works.

**Comment by nilsmagnus** [comment]
Use a fixed version for cxf by specifying it in your build.gradle
