### ISSUE TITLE
wsdl2java automatically adds generated classes directory to classpath

### ISSUE THREAD

**Issue by mkabanen** [nilsmagnus/wsdl2java#61]
This behavior should be made optional.

**Comment by nilsmagnus** [comment]
Why would you not have it on classpath? If you dont need the classes, dont generate them  :)

**Comment by mkabanen** [comment]
I'm using PMD as well as license/copyright header generator plugins and I don't want these plugins to be applied for generated classes.

**Comment by nilsmagnus** [comment]
Then I suggest you exclude these classes from beeing scanned by your PMD rules. Or you could manipulate the classpath via gradle I guess...  (maybe this will help: http://stackoverflow.com/questions/28181462/exclude-files-in-classpath-during-gradle-build)
