### ISSUE TITLE
wsdl2java always delete generatedWsdlDir

### ISSUE THREAD

**Issue by GergelyLakatos** [nilsmagnus/wsdl2java#62]
Hi all!

I have a problem with this gradle plugin. My project's structure contains the generated java interfaces, and their implementations in the same package.  So for example: _hu.main.ExampleInterface.java_
and _hu.main.impl.ExampleInterfaceImpl.java_. I dont want to add the generated interfaces to the git repo just the implementations. My goal that everytime when the project is cloned (from git server) and gradle wsdl2java is run instead of deleting the whole package (including the implementations) because of init, just the interface should be refresh.

Is it possible to set now?

**Comment by jskovjyskebankdk** [comment]
I always use a separate source folder for generated code.

Nothing good comes out of mixing generated and manually maintaned source files.

**Comment by nilsmagnus** [comment]
Agree with @jskovjyskebankdk , mixing generated code with your source is not a good idea. Closing issue.
