### ISSUE TITLE
Preventing Java header comments?

### ISSUE THREAD

**Issue by sedran** [nilsmagnus/wsdl2java#69]
Hi, 

I could not find a way to prevent this comment on generated java files:

```
/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-14T17:10:55.126+03:00
 * Generated source version: 3.2.1
 */
```

Everytime I build the project, all files change. Too many unnecessary code changes occur in version control system.

**Comment by nilsmagnus** [comment]
It is recommended not checking in the generated code to vcs.
