### ISSUE TITLE
wsdl2java with java 9: class not found javax/xml/bind/JAXBException (cxf 3.2.3)

### ISSUE THREAD

**Issue by knuthie** [nilsmagnus/wsdl2java#73]
When building using java 9, one gets:

* What went wrong:
15:55:20.659 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':nameSOAPAPI:wsdl2java'.
15:55:20.659 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > javax/xml/bind/JAXBException

...
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

Probably the --add-modules java.xml.bind is missing for the start of the wsdl2java, but I tried to add it as parameters, but it did not work.

**Comment by knuthie** [comment]
Sorry, user mistake. I didn't get that the plugin does not execute a java task, but instanciates the class directly.
To get it working, one needs to start gradle with --add-modules java.se.ee

**Comment by nilsmagnus** [comment]
Thanks @knuthie , if you have time, could you add your comment about how to make this work with java9 in the README file and send a pull-request?
