### ISSUE TITLE
Consider using Gradle's configuration avoidance API 

### ISSUE THREAD

**Issue by celcius112** [nilsmagnus/wsdl2java#93]
Since last year there's a new Gradle API for registering tasks called the 'Configuration Avoidance API'. This API was incubating from Gradle 4.9 to Gradle 5.1 inclusively, but since 5.0 has been quite stable.

This API basically lets us defined tasks configuration lazily so that they are configured only if needed. While a tasks.create("myEagerTask") would always launch myEagerTask configuration, a tasks.register("myLazyTask) would configure it only if necessary. For instance launching the simple ./gradlew help would configure myEagerTask even though they are not related, but will not configure myLazyTask. Similarly, launching ./gradlew myLazyTask will configure myLazyTask and myEagerTask.

The wsdl2java plugin configures all tasks eagerly. Their configurations does not take too much time (a ./gradlew help --scan shows they are configured in around 0.04sec), but little by little, by using other plugins that aren't using this new API, we end up with several unnecessary tasks configured eagerly. It is also worth noting that the create API will one day be deprecated.

Since this API is only usable after Gradle 4.9, using it might bring breaking changes to the users. I don't see a minimum version recommendation for the wsdl2java plugin, so before proposing a PR I wanted to discuss a bit about it.
I see two solutions:

- Only configure lazily if the user is using Gradle >4.9
- Always configure lazily but setting the minimum Gradle version to 4.9. This would induce at least a minor version upgrade since the plugin is not officially released. This is my preferred solution since Gradle 6 is coming pretty soon

**Comment by nilsmagnus** [comment]
I agree with you, the second option is probably the best. 

If you have time and motivation to write a PR for this I will gladly accept it.

**Comment by celcius112** [comment]
I’ll provide a PR with pleasure. Thank you for Your answer :).

**Comment by rubengees** [comment]
This is done and released.
