### ISSUE TITLE
wsdl2java not compatible with gradle 6+

### ISSUE THREAD

**Issue by MortenKJ** [nilsmagnus/wsdl2java#96]
Hello,

We've encountered issues with wsdl2java and gradle versions 6+. More specifically with setting the cxf version.

It seems that even when configuring the plugin extension, the cxf version is set to the default value "+"  (https://github.com/nilsmagnus/wsdl2java/blob/master/src/main/groovy/no/nils/wsdl2java/Wsdl2JavaPluginExtension.groovy#L31)

What we've encountered is that when building, we get this error: 
```org/apache/cxf/tools/wsdlto/WSDLToJava has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0```

We're running with Java 8 in our project. Our configuration of the plugins looks like this:
```
project.task('pre_wsdl2java') {
  doLast {
    project.wsdl2javaExt {
      cxfVersion = project.versions.cxf
    }
    ...
    ...
    ...
  }
}

project.wsdl2java {
  dependsOn(project.pre_wsdl2java)
}
```
project.versions.cxf is set to version 3.3.2, however, we see in the gradle cache that it uses version 3.3.6.fuse-jdk11.800001.

A quick fix for us has been:
```
buildscript {
  dependencies {
    classpath 'org.apache.cxf:cxf-tools-wsdlto-databinding-jaxb:3.3.2'
    classpath 'org.apache.cxf:cxf-tools-wsdlto-frontend-jaxws:3.3.2'
  }
}
```

Is it possible to have the latest PR https://github.com/nilsmagnus/wsdl2java/pull/95 released as a version 0.11?

**Comment by nilsmagnus** [comment]
Hi @MortenKJ!

A new release was published today with the #95 merged, thanks to @rubengees . 

:tada: 

Please upgrade and let me and @rubengees know if it works for you.
